[package]
name = "radiant-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-unknown-none"
